import {
  Page,
  Sort,
  Edit,
  Toolbar,
  Filter,
  // Resize,
  // Group,
} from "@syncfusion/ej2-react-grids";

export const gridAttributes = {
  // width: "auto",
  // allowResizing: true,
  // allowFiltering: true,
  allowSorting: true,
  allowPaging: true,
  pageSettings: { pageSize: 20, pageSizes: true },
  // allowSelection: true,
  // selectionSettings: { type: "Multiple" },
  // editSettings: {
  // allowEditing: true,
  // allowAdding: true,
  // allowDeleting: true,
  // mode: "Batch",
  // },
  // toolbar: [
  // "Add",
  // "Edit",
  // "Delete",
  // "Update",
  // "Cancel",
  // "Search",
  // ],
};

export const tableServices = [
  Page,
  // Edit,
  // Toolbar,
  // Sort,
  // Resize,
  // Filter,
  // Group,
];

export const columns = [
  // { type: "checkbox", width: "50" },
  {
    field: "id",
    headerText: "Id",
    width: "200",
    textAlign: "Left",
    allowEditing: false,
  },
  {
    field: "product.name",
    headerText: "Product",
    width: "150",
    textAlign: "Left",
    editType: "TextBox",
    allowEditing: false,
  },
  {
    field: "store.name",
    headerText: "Store",
    width: "150",
    textAlign: "Center",
    type: "string",
    allowEditing: false,
  },
  {
    field: "product.price",
    headerText: "Price",
    width: "100",
    textAlign: "Address",
    type: "number",
    allowEditing: false,
  },
  {
    field: "product.cost",
    headerText: "Cost",
    width: "100",
    textAlign: "Center",
    type: "number",
    allowEditing: false,
  },
  {
    field: "product.status",
    headerText: "Status",
    width: "100",
    textAlign: "Center",
    type: "string",
    editType: "TextBox",
    allowEditing: false,
  },
  {
    field: "product.category",
    headerText: "Category",
    width: "100",
    type: "string",
    textAlign: "Center",
    editType: "TextBox",
    allowEditing: false,
  },
  {
    field: "balance",
    headerText: "Balance",
    width: "100",
    textAlign: "Center",
    type: "number",
    minValue: 0,
    editType: "numericedit",
    validationRules: { required: true },
  },
  {
    field: "created_at",
    headerText: "Create At",
    width: "150",
    textAlign: "Center",
    type: "Date",
    format: "dd/MM/yyyy HH:mm:ss",
    allowEditing: false,
  },
  {
    field: "updated_at",
    headerText: "Updated_at At",
    width: "150",
    textAlign: "Center",
    type: "Date",
    format: "dd/MM/yyyy HH:mm:ss",
    allowEditing: false,
  },
];
